version: '3'

services:
  api:
    restart: always
    container_name: api
    build: ./api
    ports:
      - 5555:5000
    depends_on:
      - mysql
  
  frontend:
    restart: always
    build: ./frontend
    container_name: frontend
    ports:
      - 8954:8954
    depends_on:
      - api
    
  mysql:
    restart: always
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    restart: always
    container_name: adminer
    image: adminer
    ports:
      - 8725:8080

volumes:
  mysql_data: 